### ISSUE TITLE
Support build with GHC-8.4.3

### ISSUE THREAD

**Issue by chshersh** [thumphries/hgrep#81]
Current upper bound on `base` package is `<4.11`. It would be nice to support build with GHC-8.4.3 as well.

**Comment by kindaro** [comment]
I just built it with GHC 8.6.5, on top of the previous work by @niteria. It only requires a tiny patch due to changes in GHC API. [See here.](https://github.com/kindaro/hgrep/commit/becd04ee5e77de95d7951239b72fe319b5c0eeeb) The packaging could use some polishing to match the industry standard though.

Unfortunately, it does not work anyway, more specifically, it does not recognize syntactic language extensions such as `BlockArguments`:

    .../Main.hs:(30,15)-(35,48): Unexpected do block in function application:
        do (iperf, maxSpeed) <- Iperf.choose
           entries <- getEntries
           message $ (tshow . take 1 . reverse) entries
    You could write it with parentheses
    Or perhaps you meant to enable BlockArguments?

This may be due to #25, so I am not sure if my patch is to blame.

@thumphries Are you interested in us pursuing this work further together? I would be happy to do what I can, but without your advice it is hopeless for me to press forward.

**Comment by thumphries** [comment]
Hi! Sorry, I didn't see this issue until now.

Language extensions and CPP demoralised me enough in 2017 to stop working on this tool. I am happy to merge working PRs and perhaps get back into it though. The goal of hgrep was actually to enable a future `hsed` semantic scalpel tool, which I'd still like to use if it existed.

Like GHCi, syntactic extensions don't work unless they are explicitly included in each source file. IIRC we can enable them on a file by file basis, so they could perhaps be accepted as command line arguments. We also might be able to just **turn on all the syntactic extensions at the same time** if they don't break one another!

CPP is harder. It's actually evaluated already (GHC parser does it) but cabal macros and platform constants are not present, so many libraries can't be parsed properly. Solving this will require either ingenuity or project awareness.

I don't think project awareness should be in scope. There are too many formats and they all resist analysis (cabal, hpack, bazel, nix, ...). This tool should be source-only. So we'd have to try to be clever. 

One potential solution that is worth a try:
- We generate the macros from user configuration
- We write and ship a separate utility that produces a set of global macros from a Stackage snapshot
- We include a reasonably recent version of those macros with the tool so the results are plausible

**Comment by thumphries** [comment]
Happy to merge that commit of yours if you also get CI passing.

Would probably need CPP for GHC API versions, or to lock down the dependency so it's correct (don't mind which)

**Comment by kindaro** [comment]
@thumphries I can do that.

Would it be fine if I re-write Travis configuration from scratch? I would use [`haskell-ci`][haskell-ci] to generate it automatically. It would [look like this][branch], and [work like this][travis].

Notice there is one red entry at the moment. This is due to a [bug in GHC][bug], so I am going to remove this GHC version from the list of compilers to test with.

If you wish for other configurations to be added, please tell me which, and I will do my best to incorporate them.

[haskell-ci]: https://github.com/haskell-CI/haskell-ci
[branch]: https://github.com/kindaro/hgrep/commit/191cbbf8484e7db96fc4c63e9fab03b40cf0253d
[bug]: https://gitlab.haskell.org/ghc/ghc/issues/17639
[travis]: https://travis-ci.com/kindaro/hgrep/builds/143217205

**Comment by thumphries** [comment]
Yep go for it!

**Comment by kindaro** [comment]
@thumphries I have done my part, the pull request is getting cold, can you please comment?

**Comment by thumphries** [comment]
I merge PRs on weekends usually. Feel free to work on your own fork or branch if that’s too slow

**Comment by thumphries** [comment]
Done in #82

**Comment by kindaro** [comment]
@thumphries I am good with weekends. I was worried that my messages were not delivered, or that there is something wrong with the code.
