### ISSUE TITLE
Nix/enabled false

### ISSUE THREAD

**Issue by eviefp** [thumphries/hgrep#83]
What's the reason for setting `nix/enable: false` in `stack.yaml`? I had to revert/remove that line in order to work under my NixOS install.

**Comment by vaibhavsagar** [comment]
Setting `false` means it's not enabled by default. You can override this without editing `stack.yaml` by running `stack` with the `--nix` flag. The reason is that setting it to `true` would make it unusable by anyone who does not have Nix installed without first editing `stack.yaml`, and more people use Stack without Nix than with Nix.
